# Generated by Django 4.2.4 on 2023-08-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_title', models.CharField(max_length=255)),
                ('restaurant_place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_title', models.CharField(max_length=255)),
                ('menu_text', models.TextField(max_length=3000)),
                ('menu_vote_count', models.IntegerField()),
                ('menu_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_registeration_time', models.DateTimeField(auto_now_add=True)),
                ('employee_first_name', models.CharField(max_length=255)),
                ('employee_last_name', models.CharField(max_length=255)),
                ('employee_vote', models.IntegerField(default=0)),
                ('employee_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
